/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#fef7ff",
        surface: "#fef7ff",
        "surface-dim": "#dfd7e6",
        "surface-bright": "#fef7ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f9f1ff",
        "surface-container": "#f3ebfa",
        "surface-container-high": "#ede5f4",
        "surface-container-highest": "#e7e0ee",
        "on-surface": "#1d1a24",
        "on-surface-variant": "#4a4455",
        "inverse-surface": "#332f3a",
        "inverse-on-surface": "#f6eefd",
        outline: "#7b7487",
        "outline-variant": "#ccc3d8",
        "surface-tint": "#732ee4",
        primary: "#630ed4",
        "on-primary": "#ffffff",
        "primary-container": "#7c3aed",
        "on-primary-container": "#ede0ff",
        "inverse-primary": "#d2bbff",
        secondary: "#b5005d",
        "on-secondary": "#ffffff",
        "secondary-container": "#da2676",
        "on-secondary-container": "#fffbff",
        tertiary: "#005479",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#006d9c",
        "on-tertiary-container": "#cfe9ff",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#eaddff",
        "primary-fixed-dim": "#d2bbff",
        "on-primary-fixed": "#25005a",
        "on-primary-fixed-variant": "#5a00c6",
        "secondary-fixed": "#ffd9e2",
        "secondary-fixed-dim": "#ffb1c7",
        "on-secondary-fixed": "#3f001c",
        "on-secondary-fixed-variant": "#8e0048",
        "tertiary-fixed": "#c9e6ff",
        "tertiary-fixed-dim": "#89ceff",
        "on-tertiary-fixed": "#001e2f",
        "on-tertiary-fixed-variant": "#004c6e",
        "on-background": "#1d1a24",
        "surface-variant": "#e7e0ee",
      },
      spacing: {
        unit: "8px",
        gutter: "32px",
        "stack-lg": "80px",
        "margin-mobile": "20px",
        "margin-desktop": "60px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        display: ['"Nunito Sans"', "system-ui", "sans-serif"],
        heading: ['"Nunito Sans"', "system-ui", "sans-serif"],
        body: ['"DM Sans"', "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg": [
          "72px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "900" },
        ],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "800" }],
        "headline-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "800" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" },
        ],
      },
      keyframes: {
        "page-flip-in": {
          "0%": {
            opacity: "0",
            transform:
              "perspective(1200px) rotateY(-14deg) translateZ(-48px) scale(0.98)",
          },
          "100%": {
            opacity: "1",
            transform: "perspective(1200px) rotateY(0) translateZ(0) scale(1)",
          },
        },
        "loader-breathe": {
          "0%, 100%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.06)" },
        },
        "loader-spin": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
      },
      animation: {
        "page-flip-in": "page-flip-in 0.55s cubic-bezier(0.22, 1, 0.36, 1) both",
        "loader-breathe": "loader-breathe 1.2s ease-in-out infinite",
        "loader-spin": "loader-spin 1.1s linear infinite",
      },
    },
  },
  plugins: [],
};
